name: interact_cli
description: A collection of customizable interactive command-line components.
version: 2.3.0
repository: https://github.com/payam-zahedi/interact

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  dart_console: ^1.1.2
  meta: ^1.8.0
  tint: ^2.0.0

dev_dependencies:
  lint: ^2.0.1
  test: ^1.22.2
